### ISSUE TITLE
Command Argument Variables

### ISSUE THREAD

**Issue by ouijan** [ouijan/rabbit#24]
It would be awesome to be able to declare a hop command with variables and have those passed to the proxied command. This could be quite useful for commands with many arguments the user wishes to re-order or shuffle around. For Example:

```
commands:
  - hop: welcome {name} {message}
    to: echo {message}, {name}

Input: rabbit welcome Ouijan 'Good Morning'
Output: Good Morning, Ouijan
```

It may be a good idea to add a 'catch all' argument named {args} that captures all remaining input and appends it to the end of a command, unless it is already being output in the proxied command. For Example:

```
commands:
  - hop: welcome {name}
    to: echo {args}, {name}

Input: rabbit welcome Ouijan Good Morning
Output: Good Morning, Ouijan
```

The {args} variable could store a list and be accessible by index or simply output all (As used above). This will need to be considered to determine the best user workflow. If the list style accessing is to be implemented it may be handy to have a 'remaining key' which outputs the keys that are not referenced specifically.

```
commands:
  - hop: welcome {name}
    to: echo {args[1]} {name}

Input: rabbit welcome Ouijan Good Morning
Output: Morning Ouijan
```
